version: '3'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: phone_store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/phone_store
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456

volumes:
  db-data:
